version: "3.1"
services:
  redis:
    image: redis
    command: redis-server
    volumes:
      - ./deployment/redis:/data
    ports:
      - "6379:6379"
    restart: always  # always表容器运行发生错误时一直重启
    networks:
      - db_network

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: test  # 数据库名称
      MYSQL_ROOT_PASSWORD: lhl666666  # 数据库密码
      MYSQL_USER: lihl
      MYSQL_PASSWORD: lhl666666
      TZ: Asia/Shanghai
    command:
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./deployment/mysql/data:/var/lib/mysql  # 挂载数据库数据
      - ./deployment/mysql/conf/my.cnf:/etc/mysql/my.cnf  # 挂载配置文件
      - ./deployment/mysql/mysql-files:/var/lib/mysql-files/
      - ./deployment/mysql/init:/docker-entrypoint-initdb.d # 挂载数据初始化sql脚本
    ports:
      - "3306:3306"
    restart: always
    networks:
      - db_network


  nginx:
    build: deployment/nginx
    ports:
      - "80:80"
    #  - "443:443"
    expose:
      - "8000"
    volumes:
      - ./static:/usr/share/nginx/html/static  # 挂载静态文件
      - ./static/media:/usr/share/nginx/html/media  # 挂载上传文件
      # - ./deployment/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      # - ./deployment/nginx/ssl:/usr/share/nginx/ssl # 挂载ssl证书目录
    links:
      - web
    depends_on:
      - web
    restart: always
    networks:
      - web_network

  web:
    build: .
    expose:
      - "8000"
    volumes:
      - .:/app
    #  - ./deployment/tmp/logs:/tmp
    command: sh start.sh
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    restart: always
    networks:
      - web_network
      - db_network



networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

